apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ index $.Values "cluster-configs" "configmaps" "mono-ing-name" }}
  namespace: {{ index $.Values "cluster-configs" "configmaps" "namespace" }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - {{ index $.Values "cluster-configs" "configmaps" "host-name" }}
    secretName: wildcard-orbit-prod-tls
  rules:
  - host: {{ index $.Values "cluster-configs" "configmaps" "host-name" }}
    http:
      paths:
      - backend:
          serviceName: {{ index $.Values "cluster-configs" "configmaps" "mono-svc-name" }}
          servicePort: 80