apiVersion: v1
kind: Secret
metadata:
  name: ocirsecret
  namespace: {{ index $.Values "cluster-configs" "configmaps" "namespace" }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJib20ub2Npci5pbyI6eyJ1c2VybmFtZSI6ImlkZ3Jvc25mMGx3di9jaWNkaW50ZXJuYWwiLCJwYXNzd29yZCI6IjQpU1lUU01WKDFzXHUwMDNjK2EyOGIoIzYiLCJlbWFpbCI6InBhdmFuLmJvbGxhQG9yYml0YW5hbHl0aWNzLmNvbSIsImF1dGgiOiJhV1JuY205emJtWXdiSGQyTDJOcFkyUnBiblJsY201aGJEbzBLVk5aVkZOTlZpZ3hjendyWVRJNFlpZ2pOZz09In19fQ==