apiVersion: v1
kind: Service
metadata:
  name: {{ index $.Values "cluster-configs" "configmaps" "web-svc-name" }}
  namespace: {{ index $.Values "cluster-configs" "configmaps" "namespace" }}
spec:
  selector:
    app: {{ index $.Values "cluster-configs" "configmaps" "web-deployment-name" }}
  ports:
    - port: 80
      targetPort: 5050
  type: ClusterIP