{{- with index .Values "cluster-configs" "configmaps" "orbit-config" }}
{{- if .data }}
---
{{- range $ns := .namespace }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ index $.Values "cluster-configs" "configmaps" "name-config" }}
  namespace: {{ index $.Values "cluster-configs" "configmaps" "namespace" }}
data:
{{- range $key, $value := index $.Values "cluster-configs" "configmaps" "orbit-config" "data" }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
