apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "5m"
    "inhibit_rules":
    - "equal":
      - "namespace"
      - "alertname"
      "source_match":
        "severity": "critical"
      "target_match_re":
        "severity": "warning|info"
    - "equal":
      - "namespace"
      - "alertname"
      "source_match":
        "severity": "warning"
      "target_match_re":
        "severity": "info"
    "route":
       "receiver": "jenkins-api"
    "receivers":
    - "name": "jenkins-api"
      "webhook_configs":
      - "url": "http://admin:114affc6423c5cbcb6a16a6ddb2feddbbe@jenkins.orbit8.com/job/Alerttest/build?token=114affc6423c5cbcb6a16a6ddb2feddbbe"
type: Opaque
