apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: {{ index $.Values "cluster-configs" "configmaps" "pvc-name" }}
 namespace: {{ index $.Values "cluster-configs" "configmaps" "namespace" }}
spec:
 storageClassName: oci-fss
 accessModes:
 - ReadWriteMany
 resources:
  requests:
    storage: 50Gi
 volumeName: {{ index $.Values "cluster-configs" "configmaps" "pv-name" }}